standalone_tags:
  [
    {id: 0, size: 0.168},
    {id: 1, size: 0.168},
    {id: 2, size: 0.168},
    {id: 3, size: 0.168},
    {id: 4, size: 0.168},
    {id: 5, size: 0.168},
    {id: 6, size: 0.168},
    {id: 7, size: 0.168},
    {id: 8, size: 0.168},
    {id: 9, size: 0.168},
    {id: 10, size: 0.168},
    {id: 11, size: 0.168},
    {id: 12, size: 0.168},
    {id: 13, size: 0.168},
    {id: 14, size: 0.168},
    {id: 15, size: 0.168},
    {id: 16, size: 0.168},
    {id: 17, size: 0.168},
    {id: 18, size: 0.168},
    {id: 19, size: 0.168},
  ]
tag_bundles:
  []